package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lucas
 */
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Computador;
import model.dao.ComputadorDAO;
public class Registro extends javax.swing.JFrame {
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        readJtable();
        /*ComBox_Empresa.setEditable(true);
        JComBox_Sala.setEditable(true);*/
    }
    
//consulta
    ComputadorDAO dao = new ComputadorDAO();

public void readJtable(){
        DefaultTableModel modelo = (DefaultTableModel) JTbl_Consulta.getModel();
        modelo.setNumRows(0);
        JTbl_Consulta.setRowSorter(new TableRowSorter(modelo));

        for (Computador p : dao.read()){
            modelo.addRow(new Object[]{
                p.getIdComputador(),
                p.getTipo(),
                p.getEmpresa(),
                p.getSala(),
                p.getPlacaMae(),
                p.getHD(),
                p.getPlacaRede(),
                p.getRAM(),
                p.getFonte(),
                p.getPlacaVideo(),
                p.getProcessador(),
                p.getDrive()
            });
        }
    }

//busca
public void readJtableForCod(String cod){
    
        DefaultTableModel modelo = (DefaultTableModel) JTbl_Consulta.getModel();
        modelo.setNumRows(0);
        JTbl_Consulta.setRowSorter(new TableRowSorter(modelo));

        for (Computador p : dao.readForCod(cod)){
            modelo.addRow(new Object[]{
                p.getIdComputador(),
                p.getTipo(),
                p.getEmpresa(),
                p.getSala(),
                p.getPlacaMae(),
                p.getHD(),
                p.getPlacaRede(),
                p.getRAM(),
                p.getFonte(),
                p.getPlacaVideo(),
                p.getProcessador(),
                p.getDrive()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG_Tipo = new javax.swing.ButtonGroup();
        JBT_Cadastrar = new javax.swing.JButton();
        JBT_Sair = new javax.swing.JButton();
        JBT_Voltar = new javax.swing.JButton();
        JLB_Cod = new javax.swing.JLabel();
        JLB_Lab = new javax.swing.JLabel();
        JLB_Tipo = new javax.swing.JLabel();
        JTF_Cod = new javax.swing.JTextField();
        JRB_Patrimonio = new javax.swing.JRadioButton();
        JRB_Alugado = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        JCB_RAM = new javax.swing.JCheckBox();
        JCB_Fonte = new javax.swing.JCheckBox();
        JCB_PlacaVideo = new javax.swing.JCheckBox();
        JCB_Processador = new javax.swing.JCheckBox();
        JCB_Drive = new javax.swing.JCheckBox();
        JLB_Componentes = new javax.swing.JLabel();
        JCB_PlacaMae = new javax.swing.JCheckBox();
        JCB_HD = new javax.swing.JCheckBox();
        JCB_PlacaRede = new javax.swing.JCheckBox();
        JComBox_Empresa = new javax.swing.JComboBox<>();
        JComBox_Sala = new javax.swing.JComboBox<>();
        JBT_Limpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTbl_Consulta = new javax.swing.JTable();
        Alterar = new javax.swing.JButton();
        Deletar = new javax.swing.JButton();
        JTF_Buscar = new javax.swing.JTextField();
        JBT_Buscar = new javax.swing.JButton();
        JBT_Exportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar");

        JBT_Cadastrar.setText("Registrar");
        JBT_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_CadastrarActionPerformed(evt);
            }
        });

        JBT_Sair.setText("Sair");
        JBT_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_SairActionPerformed(evt);
            }
        });

        JBT_Voltar.setText("Voltar");
        JBT_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_VoltarActionPerformed(evt);
            }
        });

        JLB_Cod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JLB_Cod.setText("Cód. Computador:");

        JLB_Lab.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JLB_Lab.setText("Sala:");

        JLB_Tipo.setText("Tipo:");

        JTF_Cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CodActionPerformed(evt);
            }
        });

        BG_Tipo.add(JRB_Patrimonio);
        JRB_Patrimonio.setText("Patrimônio");
        JRB_Patrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_PatrimonioActionPerformed(evt);
            }
        });

        BG_Tipo.add(JRB_Alugado);
        JRB_Alugado.setText("Alugado");
        JRB_Alugado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_AlugadoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JCB_RAM.setText("RAM");
        JCB_RAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_RAMActionPerformed(evt);
            }
        });

        JCB_Fonte.setText("Fonte");

        JCB_PlacaVideo.setText("Placa de Vídeo");
        JCB_PlacaVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_PlacaVideoActionPerformed(evt);
            }
        });

        JCB_Processador.setText("Processador");
        JCB_Processador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_ProcessadorActionPerformed(evt);
            }
        });

        JCB_Drive.setText("Drive");

        JLB_Componentes.setText("Componentes:");

        JCB_PlacaMae.setText("Placa Mãe");
        JCB_PlacaMae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_PlacaMaeActionPerformed(evt);
            }
        });

        JCB_HD.setText("HD");
        JCB_HD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_HDActionPerformed(evt);
            }
        });

        JCB_PlacaRede.setText("Placa de Rede");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCB_PlacaMae)
                    .addComponent(JCB_HD)
                    .addComponent(JCB_PlacaRede)
                    .addComponent(JCB_RAM, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCB_Fonte)
                    .addComponent(JCB_Drive)
                    .addComponent(JCB_Processador)
                    .addComponent(JCB_PlacaVideo))
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JLB_Componentes)
                    .addContainerGap(350, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JCB_PlacaMae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCB_HD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCB_PlacaRede)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCB_RAM))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(JCB_Fonte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCB_PlacaVideo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCB_Processador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCB_Drive)))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JLB_Componentes)
                    .addContainerGap(128, Short.MAX_VALUE)))
        );

        JComBox_Empresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma empresa:", "Investiram", "Maxxwal", "Empresa 3" }));
        JComBox_Empresa.setEnabled(false);
        JComBox_Empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComBox_EmpresaActionPerformed(evt);
            }
        });

        JComBox_Sala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma sala:", "Lab. 1", "Lab. 2", "Lab. 3", "Lab. 4", "SOE", "SOP", "Direção", "Secretaria", "Coordenação de Informática", "Coordenação de Administração", "Coordenação de Eletrotécnica", "Coordenação de Análises Clínicas" }));
        JComBox_Sala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComBox_SalaActionPerformed(evt);
            }
        });

        JBT_Limpar.setText("Limpar");
        JBT_Limpar.setPreferredSize(new java.awt.Dimension(81, 23));
        JBT_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_LimparActionPerformed(evt);
            }
        });

        JTbl_Consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Tipo", "Empresa", "Sala", "Pl. Mãe", "HD", "Pl. Rede", "RAM", "Fonte", "Pl. Vídeo", "CPU", "Drive"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTbl_Consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTbl_ConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTbl_Consulta);
        if (JTbl_Consulta.getColumnModel().getColumnCount() > 0) {
            JTbl_Consulta.getColumnModel().getColumn(0).setResizable(false);
            JTbl_Consulta.getColumnModel().getColumn(1).setResizable(false);
            JTbl_Consulta.getColumnModel().getColumn(2).setResizable(false);
            JTbl_Consulta.getColumnModel().getColumn(3).setResizable(false);
            JTbl_Consulta.getColumnModel().getColumn(4).setResizable(false);
            JTbl_Consulta.getColumnModel().getColumn(5).setResizable(false);
            JTbl_Consulta.getColumnModel().getColumn(6).setResizable(false);
            JTbl_Consulta.getColumnModel().getColumn(7).setResizable(false);
            JTbl_Consulta.getColumnModel().getColumn(8).setResizable(false);
            JTbl_Consulta.getColumnModel().getColumn(9).setResizable(false);
            JTbl_Consulta.getColumnModel().getColumn(10).setResizable(false);
            JTbl_Consulta.getColumnModel().getColumn(11).setResizable(false);
        }

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        Deletar.setText("Deletar");
        Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletarActionPerformed(evt);
            }
        });

        JTF_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_BuscarActionPerformed(evt);
            }
        });

        JBT_Buscar.setText("Buscar");
        JBT_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_BuscarActionPerformed(evt);
            }
        });

        JBT_Exportar.setText("Export");
        JBT_Exportar.setPreferredSize(new java.awt.Dimension(67, 23));
        JBT_Exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_ExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLB_Tipo)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JRB_Alugado)
                                        .addGap(18, 18, 18)
                                        .addComponent(JComBox_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JRB_Patrimonio)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLB_Lab)
                                .addGap(10, 10, 10)
                                .addComponent(JComBox_Sala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLB_Cod)
                                .addGap(10, 10, 10)
                                .addComponent(JTF_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JTF_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBT_Buscar)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBT_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBT_Exportar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBT_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBT_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBT_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLB_Cod)
                            .addComponent(JTF_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLB_Tipo)
                            .addComponent(JRB_Patrimonio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JRB_Alugado)
                            .addComponent(JComBox_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLB_Lab)
                            .addComponent(JComBox_Sala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBT_Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JBT_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JBT_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JBT_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JBT_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBT_Exportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Deletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(992, 652));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBT_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JBT_SairActionPerformed

    private void JBT_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_VoltarActionPerformed
Menu menu = new Menu();
menu.setVisible(true);
dispose();
    }//GEN-LAST:event_JBT_VoltarActionPerformed

    private void JTF_CodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CodActionPerformed

    private void JCB_HDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_HDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCB_HDActionPerformed

    private void JCB_PlacaMaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_PlacaMaeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCB_PlacaMaeActionPerformed

    private void JCB_RAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_RAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCB_RAMActionPerformed

    private void JCB_PlacaVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_PlacaVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCB_PlacaVideoActionPerformed

    private void JCB_ProcessadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_ProcessadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCB_ProcessadorActionPerformed

    private void JBT_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_CadastrarActionPerformed
        if(JTF_Cod.getText().equals("") || JComBox_Sala.getSelectedItem().equals("Selecione uma sala:") ||(!JRB_Alugado.isSelected() && !JRB_Patrimonio.isSelected())){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios.");
        }else if(JRB_Alugado.isSelected() && JComBox_Empresa.getSelectedItem().equals("Selecione uma empresa:")){
            JOptionPane.showMessageDialog(null, "Selecione uma empresa.");
        }else{
//id computador
            Computador c = new Computador();
            ComputadorDAO dao = new ComputadorDAO();
            c.setIdComputador(JTF_Cod.getText());
        
//sala
            c.setSala(JComBox_Sala.getSelectedItem().toString());
        
//tipo
            if(JRB_Alugado.isSelected()){
                c.setTipo("Alugado");
                c.setEmpresa(JComBox_Empresa.getSelectedItem().toString());
            
            }else if(JRB_Patrimonio.isSelected()){
                c.setTipo("Patrimônio");
            }
        
//componentes
    //hd
            if(JCB_HD.isSelected()){
                c.setHD(true);
            }else{
                c.setHD(false);
            }
    //placa video
            if(JCB_PlacaVideo.isSelected()){
                c.setPlacaVideo(true);
            }else{
                c.setPlacaVideo(false);
            }
    //placa mae
            if(JCB_PlacaMae.isSelected()){
                c.setPlacaMae(true);
            }else{
                c.setPlacaMae(false);
        }
    //RAM
            if(JCB_RAM.isSelected()){
                c.setRAM(true);
            }else{
                c.setRAM(false);
        }
    //drive
            if(JCB_Drive.isSelected()){
                c.setDrive(true);
            }else{
                c.setDrive(false);
            }
    //fonte
            if(JCB_Fonte.isSelected()){
                c.setFonte(true);
            }else{
                c.setFonte(false);
            }
    //processador
            if(JCB_Processador.isSelected()){
                c.setProcessador(true);
            }else{
                c.setProcessador(false);
            }
    //placa rede
            if(JCB_PlacaRede.isSelected()){
                c.setPlacaRede(true);
            }else{
                c.setPlacaRede(false);
            }
        
            dao.create(c);
        
            readJtable();
        
//limpar
    JTF_Cod.setText(null);
    BG_Tipo.clearSelection();
    JComBox_Empresa.setSelectedItem("Selecione uma empresa:");
    JComBox_Empresa.setEnabled(false);
    JComBox_Sala.setSelectedItem("Selecione uma sala:");
    JTF_Buscar.setText(null);
        }
//componentes
    JCB_PlacaMae.setSelected(false);
    JCB_HD.setSelected(false);
    JCB_PlacaVideo.setSelected(false);
    JCB_PlacaRede.setSelected(false);
    JCB_Drive.setSelected(false);
    JCB_Processador.setSelected(false);
    JCB_RAM.setSelected(false);
    JCB_Fonte.setSelected(false);   
    
    }//GEN-LAST:event_JBT_CadastrarActionPerformed

    private void JComBox_EmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComBox_EmpresaActionPerformed
    
    }//GEN-LAST:event_JComBox_EmpresaActionPerformed

    private void JComBox_SalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComBox_SalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComBox_SalaActionPerformed

    private void JBT_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_LimparActionPerformed
    JTF_Cod.setText(null);
    BG_Tipo.clearSelection();
    JComBox_Empresa.setSelectedItem("Selecione uma empresa:");
    JComBox_Empresa.setEnabled(false);
    JComBox_Sala.setSelectedItem("Selecione uma sala:");
    JTF_Buscar.setText(null);
//componentes
    JCB_PlacaMae.setSelected(false);
    JCB_HD.setSelected(false);
    JCB_PlacaVideo.setSelected(false);
    JCB_PlacaRede.setSelected(false);
    JCB_Drive.setSelected(false);
    JCB_Processador.setSelected(false);
    JCB_RAM.setSelected(false);
    JCB_Fonte.setSelected(false);
    }//GEN-LAST:event_JBT_LimparActionPerformed

    private void JRB_PatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_PatrimonioActionPerformed
    if(JRB_Patrimonio.isSelected()){
        JComBox_Empresa.setEnabled(false);
    }
    JComBox_Empresa.setSelectedItem("Selecione uma empresa:");
    }//GEN-LAST:event_JRB_PatrimonioActionPerformed

    private void JTbl_ConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTbl_ConsultaMouseClicked
Computador p = new Computador();
        JTF_Cod.setText(JTbl_Consulta.getValueAt(JTbl_Consulta.getSelectedRow(), 0).toString());
        
                if ("Alugado".equals(JTbl_Consulta.getValueAt(JTbl_Consulta.getSelectedRow(), 1).toString())){
                    JRB_Alugado.setSelected(true);
                    JRB_Patrimonio.setSelected(false);
                    JComBox_Empresa.setSelectedItem(JTbl_Consulta.getValueAt(JTbl_Consulta.getSelectedRow(), 2).toString());
                    JComBox_Empresa.setEnabled(true);
                    JComBox_Sala.setSelectedItem(JTbl_Consulta.getValueAt(JTbl_Consulta.getSelectedRow(), 3));
                }
                else if("Patrimônio".equals(JTbl_Consulta.getValueAt(JTbl_Consulta.getSelectedRow(), 1).toString())){
                    JRB_Patrimonio.setSelected(true);
                    JRB_Alugado.setSelected(false);
                    JComBox_Empresa.setSelectedItem("Selecione uma empresa:");
                    JComBox_Empresa.setEnabled(false);
                    JComBox_Sala.setSelectedItem(JTbl_Consulta.getValueAt(JTbl_Consulta.getSelectedRow(), 3));
                }
                
        
        int colMae = 4;
        Object Mae = JTbl_Consulta.getValueAt(JTbl_Consulta.getSelectedRow(), colMae);
        Boolean fimMae=((Boolean) Mae).booleanValue();
        
        if(fimMae==true){
            JCB_PlacaMae.setSelected(true);
        }
        else{
            JCB_PlacaMae.setSelected(false);
        }
        int colHD = 5;
        Object HD = JTbl_Consulta.getValueAt(JTbl_Consulta.getSelectedRow(), colHD);
        Boolean fimHD=((Boolean) HD).booleanValue();
        
        if(fimHD==true){
            JCB_HD.setSelected(true);
        }
        else{
            JCB_HD.setSelected(false);
        }
        
        
        int colRede = 6;
        Object Rede = JTbl_Consulta.getValueAt(JTbl_Consulta.getSelectedRow(), colRede);
        Boolean fimRede=((Boolean) Rede).booleanValue();
        
        if(fimRede==true){
            JCB_PlacaRede.setSelected(true);
        }
        else{
            JCB_PlacaRede.setSelected(false);
        }
        
        
        int colRAM = 7;
        Object RAM = JTbl_Consulta.getValueAt(JTbl_Consulta.getSelectedRow(), colRAM);
        Boolean fimRAM=((Boolean) RAM).booleanValue();
        
        if(fimRAM==true){
            JCB_RAM.setSelected(true);
        }
        else{
            JCB_RAM.setSelected(false);
        }
        
        int colFonte = 8;
        Object Fonte = JTbl_Consulta.getValueAt(JTbl_Consulta.getSelectedRow(), colFonte);
        Boolean fimFonte=((Boolean) Fonte).booleanValue();
        
        if(fimFonte==true){
            JCB_Fonte.setSelected(true);
        }
        else{
            JCB_Fonte.setSelected(false);
        }
        
        int colVideo = 9;
        Object Video = JTbl_Consulta.getValueAt(JTbl_Consulta.getSelectedRow(), colVideo);
        Boolean fimVideo=((Boolean) Video).booleanValue();
        
        if(fimVideo==true){
            JCB_PlacaVideo.setSelected(true);
        }
        else{
            JCB_PlacaVideo.setSelected(false);
        }
        
        int colProcessador = 10;
        Object Processador = JTbl_Consulta.getValueAt(JTbl_Consulta.getSelectedRow(), colProcessador);
        Boolean fimProcessador=((Boolean) Processador).booleanValue();
        
        if(fimProcessador==true){
            JCB_Processador.setSelected(true);
        }
        else{
            JCB_Processador.setSelected(false);
        }
        
        int colDrive = 11;
        Object Drive = JTbl_Consulta.getValueAt(JTbl_Consulta.getSelectedRow(), colDrive);
        Boolean fimDrive=((Boolean) Drive).booleanValue();
        
        if(fimDrive==true){
            JCB_Drive.setSelected(true);
        }
        else{
            JCB_Drive.setSelected(false);
        }
    }//GEN-LAST:event_JTbl_ConsultaMouseClicked

    private void DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletarActionPerformed
        Computador c = new Computador();
        ComputadorDAO dao = new ComputadorDAO();
        c.setIdComputador(JTF_Cod.getText());
        
        if(JTF_Cod.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Selecione um computador ou \ndigite seu código para ser deletado.", "Atenção!", JOptionPane.WARNING_MESSAGE);
            
        }else{
            
        
        int resposta = JOptionPane.showConfirmDialog(null, "Você não poderá reverter essa ação.", "Atenção!", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        if(resposta == JOptionPane.CANCEL_OPTION){
            
        }else{
        
            dao.delete(c);
            readJtable();
        
//limpar
        JTF_Cod.setText(null);
        BG_Tipo.clearSelection();
        JComBox_Empresa.setSelectedItem("Selecione uma empresa:");
        JComBox_Sala.setSelectedItem("Selecione uma sala:");
        JTF_Buscar.setText(null);
//componentes
        JCB_PlacaMae.setSelected(false);
        JCB_HD.setSelected(false);
        JCB_PlacaVideo.setSelected(false);
        JCB_PlacaRede.setSelected(false);
        JCB_Drive.setSelected(false);
        JCB_Processador.setSelected(false);
        JCB_RAM.setSelected(false);
        JCB_Fonte.setSelected(false);
        }
        }
    }//GEN-LAST:event_DeletarActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        if(JTF_Cod.getText().equals("") || JComBox_Sala.getSelectedItem().equals("Selecione uma sala:") ||(!JRB_Alugado.isSelected() && !JRB_Patrimonio.isSelected())){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios.");
        }else if(JRB_Alugado.isSelected() && JComBox_Empresa.getSelectedItem().equals("Selecione uma empresa:")){
            JOptionPane.showMessageDialog(null, "Selecione uma empresa.");
        }else{

            Computador c = new Computador();
            ComputadorDAO dao = new ComputadorDAO();
        
//sala
            c.setSala(JComBox_Sala.getSelectedItem().toString());
        
//tipo
            if(JRB_Alugado.isSelected()){
                c.setTipo("Alugado");
                c.setEmpresa(JComBox_Empresa.getSelectedItem().toString());
            
            }else if(JRB_Patrimonio.isSelected()){
                c.setTipo("Patrimônio");
            }
        
//componentes
    //hd
            if(JCB_HD.isSelected()){
                c.setHD(true);
            }else{
                c.setHD(false);
            }
    //placa video
            if(JCB_PlacaVideo.isSelected()){
                c.setPlacaVideo(true);
            }else{
                c.setPlacaVideo(false);
            }
    //placa mae
            if(JCB_PlacaMae.isSelected()){
                c.setPlacaMae(true);
            }else{
                c.setPlacaMae(false);
            }
    //RAM
            if(JCB_RAM.isSelected()){
                c.setRAM(true);
            }else{
                c.setRAM(false);
            }
    //drive
            if(JCB_Drive.isSelected()){
                c.setDrive(true);
            }else{
                c.setDrive(false);
            }
    //fonte
            if(JCB_Fonte.isSelected()){
                c.setFonte(true);
            }else{
                c.setFonte(false);
            }
    //processador
            if(JCB_Processador.isSelected()){
                c.setProcessador(true);
            }else{
                c.setProcessador(false);
            }
    //placa rede
            if(JCB_PlacaRede.isSelected()){
                c.setPlacaRede(true);
            }else{
                c.setPlacaRede(false);
            }
//id computador
        c.setIdComputador (JTF_Cod.getText());
        
        dao.update(c);
        
        readJtable();
        }

    }//GEN-LAST:event_AlterarActionPerformed

    private void JTF_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_BuscarActionPerformed

    }//GEN-LAST:event_JTF_BuscarActionPerformed

    private void JBT_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_BuscarActionPerformed
        readJtableForCod(JTF_Buscar.getText());
    }//GEN-LAST:event_JBT_BuscarActionPerformed

    private void JRB_AlugadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_AlugadoActionPerformed
    if(JRB_Alugado.isSelected()){
        JComBox_Empresa.setEnabled(true);
    }
    }//GEN-LAST:event_JRB_AlugadoActionPerformed

    private void JBT_ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_ExportarActionPerformed
        /*JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify a file save");
        int userSelection = fileChooser.showSaveDialog(this);
        if(userSelection == JFileChooser.APPROVE_OPTION){
            File fileToSave = fileChooser.getSelectedFile();
            //lets write to file
         
            try {
                FileWriter fw = new FileWriter(fileToSave);
                BufferedWriter bw = new BufferedWriter(fw);
                for (int i=0; i < JTbl_Consulta.getColumnCount(); i++) {
                    for (int j = 0; j < JTbl_Consulta.getColumnCount(); j++) {
                        //write
                        if(JTbl_Consulta.getValueAt(i, j) == null){
                            bw.write(" ,");
                        }
                            bw.write(String.valueOf(JTbl_Consulta.getValueAt(i, j))+", ");
                    }
                    bw.newLine();//record per line 
                }
                JOptionPane.showMessageDialog(this, "SUCCESSFULLY LOADED","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
                bw.close();
                fw.close();
            } catch (IOException ex) {
               JOptionPane.showMessageDialog(this, "ERROR","ERROR MESSAGE",JOptionPane.ERROR_MESSAGE);
            }   
        }*/
        
        
        try 
        {
            File archivo = new File("C:\\Users\\lucas\\OneDrive\\Documentos\\dados.xls");
            TableModel modelo = JTbl_Consulta.getModel();
            FileWriter excel = new FileWriter(archivo);
             for(int i = 0; i < modelo.getColumnCount(); i++)
             {
                excel.write(modelo.getColumnName(i) + ", ");
             }
             excel.write("\n");
             for(int i=0; i< modelo.getRowCount(); i++) 
             {
                for(int j=0; j < modelo.getColumnCount(); j++) 
                {
                    String data = String.valueOf(modelo.getValueAt(i, j));
                    if(data == null)
                    {
                        //JOptionPane.showMessageDialog(null, JTbl_Consulta.getColumnName(j) + data);
                        data = " ";
                    }
                    //JOptionPane.showMessageDialog(null, JTbl_Consulta.getColumnName(j) + data);
                    excel.write(data.toString()+", ");
                }
                excel.write("\n");
            }

        excel.close();
            JOptionPane.showMessageDialog(null, "Arquivo criado");
            
        } catch (IOException ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        //}
    }//GEN-LAST:event_JBT_ExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.ButtonGroup BG_Tipo;
    private javax.swing.JButton Deletar;
    private javax.swing.JButton JBT_Buscar;
    private javax.swing.JButton JBT_Cadastrar;
    private javax.swing.JButton JBT_Exportar;
    private javax.swing.JButton JBT_Limpar;
    private javax.swing.JButton JBT_Sair;
    private javax.swing.JButton JBT_Voltar;
    private javax.swing.JCheckBox JCB_Drive;
    private javax.swing.JCheckBox JCB_Fonte;
    private javax.swing.JCheckBox JCB_HD;
    private javax.swing.JCheckBox JCB_PlacaMae;
    private javax.swing.JCheckBox JCB_PlacaRede;
    private javax.swing.JCheckBox JCB_PlacaVideo;
    private javax.swing.JCheckBox JCB_Processador;
    private javax.swing.JCheckBox JCB_RAM;
    private javax.swing.JComboBox<String> JComBox_Empresa;
    private javax.swing.JComboBox<String> JComBox_Sala;
    private javax.swing.JLabel JLB_Cod;
    private javax.swing.JLabel JLB_Componentes;
    private javax.swing.JLabel JLB_Lab;
    private javax.swing.JLabel JLB_Tipo;
    private javax.swing.JRadioButton JRB_Alugado;
    private javax.swing.JRadioButton JRB_Patrimonio;
    private javax.swing.JTextField JTF_Buscar;
    private javax.swing.JTextField JTF_Cod;
    private javax.swing.JTable JTbl_Consulta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
